config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :rooms do
    resources :messages
  end
  root 'rooms#index'
  devise_for :users
  get 'user/:id' , to: 'users#show' , as: 'user'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
  before_create :confirm_participant
  has_many_attached :attachments, dependent: :destroy

  def chat_attachment(index)
    target = attachments[index]
    return unless attachments.attached?
    if target.image?
      Rails.application.routes.url_helpers.rails_blob_url(target)
    elsif target.video?
      target.variant(resize_to_limit: [150, 150]).processed.url
    end
  end

  def confirm_participant
    if room.is_private
      is_participant = Participant.where(user_id: user.id, room_id: room.id).first
      throw :abort unless is_participant
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_if_public }
  has_many :participants, dependent: :destroy
  has_many :messages

  def broadcast_if_public
    broadcast_append_to 'rooms' unless is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user: user, room_id: single_room.id)
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(
      body: msg_params[:body],
      room_id: params[:room_id],
      attachments: msg_params[:attachments]
    )
  end

  private

  def msg_params
    params.require(:message).permit(:body, attachments: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
    render 'index'
  end

  def show
    @single_room = Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_rooms
    @message = Message.new

    @messages = @single_room.messages.order(created_at: :asc)
    @users = User.all_except(current_user)
    render 'index'
  end 

  def create
    @room = Room.create(name: params['room']['name'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @rooms = Room.public_rooms
    @room = Room.new
    @room_name = get_name(@user, current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)
    render 'rooms/index'
  end

  private

  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_new_message_form.html.erb
<div class="mt-4 px-4">
  <%= form_with(model: [@single_room, @message], remote: true, class: "flex space-x-2", data: {controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset'}) do |f| %>
    <div id="attachment-previews">
    </div>
    <div class="image-upload relative attach-image">
      <label for="message_attachments" class="cursor-pointer flex items-center">
        <i class="fas fa-paperclip upload-button text-2xl"></i>
        <span id="attached-filename" class="ml-[3px] text-sm"></span>
      </label>
      <%= f.file_field :attachments, multiple: true, id: 'message_attachments', class: 'hidden', onchange: "attachedFile()" %>
    </div>
    <%= f.text_field :body, id: 'chat-text', class: "flex-1 p-2 border rounded", placeholder: "Type your message...", autocomplete: 'off' %>
    <%= f.submit 'Send', data: { disable_with: false }, class: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600", onclick: "removeAttachedFile()" %>
  <% end %>
</div>

<script>
  function attachedFile(){
    item = document.getElementById('message_attachments')
    document.getElementById('attached-filename').textContent = item.value.split('\\').slice(-1)[0]
  }

  function removeAttachedFile(){
    document.getElementById('attached-filename').textContent = ""
  }
</script>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "flex items-center space-x-2", data: {controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset'}) do |f| %>
  <%= f.text_field :name, class: "form-control flex-grow px-4 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500", autocomplete: 'off' %>
  <%= f.submit "Create", class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50", data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      <%= ".message-box" %> {
          padding: 10px;
          border-radius: 15px; /* Rounded corners */
          margin: 5px 0; /* Vertical spacing between messages */
          color: black; /* Text color for better contrast */
          font-size: 16px; /* Font size for readability */
          max-width: 60%; /* Max width to make it look like a bubble */
          word-wrap: break-word; /* Ensure long words wrap to the next line */
          box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2); /* Subtle shadow for 3D effect */
          display: inline-block; /* Display as an inline-block element */
      }

      <%= ".msg-#{current_user&.id}" %> {
          background-color: #007bff !important;
          padding: 10px;
          border-radius: 15px; /* Rounded corners */
          margin: 5px 0; /* Vertical spacing between messages */
          color: white; /* Text color for better contrast */
          font-size: 16px; /* Font size for readability */
          max-width: 60%; /* Max width to make it look like a bubble */
          word-wrap: break-word; /* Ensure long words wrap to the next line */
          box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2); /* Subtle shadow for 3D effect */
          display: inline-block; /* Display as an inline-block element */
      }

      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
  </head>

  <body>
    <% if flash[:notice] %>
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
            <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <%= flash[:alert] %>
        </div>
      <% end %>
    <main class="mx-auto flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <% unless message.room.is_private %>
      <h6 class="name font-bold"> <%= message.user.email %> </h6>
    <% end %>
   <div>
      <%= message.body %>
    </div>
    <div class="custom-size">
    <% if message.attachments.attached? %>
      <% message.attachments.each_with_index do |attachment, index| %>
        <% if attachment.image? %>
          <%= image_tag(message.chat_attachment(index), class: 'attachment_file') %>
        <% elsif attachment.video? %>
          <%= video_tag(url_for(attachment), controls:'', class: 'attachment_file') %>
        <% elsif attachment.audio? %>
          <%= audio_tag(url_for(attachment), controls: '', class: 'attachment_file') %>
        <% else %>
          <%= link_to attachment.filename, url_for(attachment),class: 'attachment_file', style:"text-decoration: none; color: #fff" %>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="flex">
  <h1 class="text-3xl font-bold underline text-center mt-8 mb-4">
      Hello world!
  </h1>
  <div class="flex justify-center ml-10">
    <% if current_user %>
      <%= link_to "Start Chatting", rooms_path %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded mr-4 text-center" %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mr-4 text-center" %>
      <%= link_to "Login", new_user_session_path, class: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded text-center" %>
    <% end %>
  </div>
</div>

app/views/rooms/_room.html.erb
<div class="space-y-2">
    <div class="p-2 border-b hover:bg-gray-100">
      <%= link_to room.name, room, class: "text-blue-600 hover:underline" %>
    </div>
</div>

app/views/rooms/index.html.erb
<div class="min-h-screen flex flex-col w-[100%]">
  <!-- Navbar -->
  <nav class="bg-gray-800 text-white p-4 flex justify-between items-center h-[72px]">
    <h5><%= current_user.email %></h5>
    <div>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded mr-4 text-center" %>
    </div>
  </nav>

  <div class="layout flex flex-1" >
    <!-- Sidebar -->
    <aside class="layout w-1/4 bg-gray-100 p-4">
      <h4 class="text-xl mb-4">Users</h4>
      <%= turbo_stream_from "users" %>
      <div id="users" class="space-y-2">
        <%= render @users %>
      </div>
      <div class="mb-4 mt-5">
        <h4 class="text-xl mb-2">Rooms</h4>
        <div>
          <%= render 'layouts/new_room_form' %>
        </div>
        <%= turbo_stream_from "rooms" %>
        <div id="rooms" class="space-y-2">
          <%= render @rooms %>
        </div>
      </div>
    </aside>

    <!-- Main Chat Area -->
    <main class="layout flex-1 bg-white p-4 flex flex-col">
      <div id="room_container" class="flex-1 flex flex-col">
        <% if @single_room %>
          <div id="single_room" data-controller = "scroll" class="messagesDiv flex-1 flex flex-col border rounded py-4">
            <h4 class="text-center text-2xl mb-4"><%= @user&.email || @single_room.name %></h4>
            <%= turbo_stream_from @single_room %>
            <div id="messages" class="flex-1 overflow-y-auto mb-4 p-4">
              <%= render @messages %>
            </div>
            <%= render partial: 'layouts/new_message_form' %>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

app/views/users/_user.html.erb
<div class="space-y-2">
    <div class="p-2 border-b hover:bg-gray-100">
      <%= link_to user.email, user, class: "text-blue-600 hover:underline" %>
    </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>